description: Product information
type: object
properties:
  id:
    description: Product identifier
    type: string
  name:
    description: Product Name
    type: string
  description:
    description: Product's description
    type: string
  imageUrl:
    description: Product image's URL
    type: string
  price:
    description: Product price
    type: BigDecimal
  count:
    description: Product count
    type: integer
    format: int32
  tag:
    description: Tags associated with the product
    type: array
    items:
      $ref: './Tag.yaml'